spring:

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3309/cspm?createDatabaseIfNotExist=true
    username: root
    password: root
